---
- name: PGADAPTER - create a directory if it does not exist
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: directory
    mode: '0755'
  loop:
    - { path: "{{ ansible_workdir }}/pgadapter" }

- name: PGADAPTER - Make env file from template
  ansible.builtin.template:
    src: pgadapter.env.j2
    dest: "{{ ansible_workdir }}/pgadapter/pgadapter.env"
    owner: root
    group: root
    mode: 0600

- name: PGADAPTER - Move binary to /usr/local/bin
  ansible.builtin.copy:
    src: postgresql-prometheus-adapter
    dest: /usr/local/bin/postgresql-prometheus-adapter
    owner: root
    group: root
    mode: 0755

- name: PGADAPTER - Copy unit file to systemd
  ansible.builtin.template:
    src: pgadapter.service.j2
    dest: /etc/systemd/system/pgadapter.service
    owner: root
    group: root
    mode: 0600

- name: PGADAPTER - Start unit
  ansible.builtin.systemd:
    name: pgadapter.service
    state: started
    daemon_reload: yes
    enabled: yes
